# Generated by Django 4.1.3 on 2022-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_business', models.CharField(choices=[('business', 'business'), ('shop', 'shop')], max_length=100)),
            ],
        ),
    ]
