# Generated by Django 4.1.3 on 2022-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_rename_type_of_business_storefront_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='theme',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
