# Generated by Django 4.1.3 on 2022-12-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_storefront_theme_alter_storefront_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='theme',
            field=models.CharField(choices=[('theme1', 'theme1'), ('theme2', 'theme2'), ('theme3', 'theme3'), ('theme4', 'theme4'), ('theme5', 'theme5'), ('theme6', 'theme6'), ('theme7', 'theme7')], default='theme1', max_length=100),
        ),
    ]
