# Generated by Django 4.1.3 on 2022-12-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_storefront_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='logo',
            field=models.ImageField(default=1, upload_to='seller/storefront/'),
            preserve_default=False,
        ),
    ]
