# Generated by Django 4.1.3 on 2022-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_storefront_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='aboutUsPhoto',
            field=models.ImageField(default=1, upload_to='seller/storefront/'),
            preserve_default=False,
        ),
    ]
