# Generated by Django 4.1.3 on 2022-12-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0010_storefront_aboutusphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='registrar',
            field=models.CharField(choices=[('godaddy.com', 'godaddy.com'), ('namecheap.com', 'namecheap.com'), ('bigrock.in', 'bigrock.in')], max_length=100, null=True),
        ),
    ]
